### ISSUE TITLE
Add RSSI info into configurator 

### ISSUE THREAD

**Issue by error414** [FlightOne/FlightOne#308] opened 2018-10-13 07:12 UTC
It would be nice to add RSSI value to configurator, similar like is voltage or current values. I set taranis, RSSI is sent over ch8 but ttyOSD shows only 120% to 141%. I used the same mixer settings as for betaflight.

**Comment by Arti3DPlayer** [comment] 2018-11-07 12:48
Duplicate of #285

**Closed by Arti3DPlayer** 2018-11-07 12:48 UTC
